#!/bin/sh

# Load Wi-Fi driver modules
modprobe wl18xx
modprobe wlcore_sdio

# Bring up Ethernet and request IP
ip link set eth0 up
udhcpc -i eth0

# Wait for wlan0 interface to be ready
for i in $(seq 1 30); do
    [ -e /sys/class/net/wlan0 ] && break
    sleep 0.01
done

# Configure Wi-Fi interface and IP
ip link set wlan0 up
ip addr add 192.168.50.1/24 dev wlan0

# Start Wi-Fi access point (hostapd)
hostapd -B /etc/hostapd.conf

# Start DHCP and DNS services (dnsmasq)
dnsmasq -C /etc/dnsmasq.conf

# Enable IP forwarding
echo 1 > /proc/sys/net/ipv4/ip_forward

# Start HTTP server (serving /www on port 80)
httpd -h /www -p 80
